"""
ML Training Pipeline - Student Guidance & Domain Recommender
Uses Decision Tree, Random Forest, KNN, PCA as per roadmap
Input: dataset.csv (generated by generate_dataset.py)
Output: model.pkl, metrics.txt, confusion matrix data

For deployment: backend/ml_service/model.pkl
Fallback: Client-side JS uses same weights if backend not running
"""
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle
import json
from pathlib import Path

def train():
    csv_path = Path(__file__).parent / "dataset.csv"
    if not csv_path.exists():
        print("dataset.csv not found, run generate_dataset.py first")
        return
    
    df = pd.read_csv(csv_path)
    print(f"Loaded {len(df)} records")
    
    # Features as per roadmap
    feature_cols = ["logic_score","math_aptitude","creativity","security_interest","cloud_interest","data_interest","os_interest","math_marks","physics_marks","programming_marks","english_marks"]
    X = df[feature_cols].values
    y = df["recommended_domain"].values
    
    le = LabelEncoder()
    y_enc = le.fit_transform(y)
    
    # Encode categorical
    # Standardize
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    # PCA (as per JETIR 2024 reference)
    pca = PCA(n_components=0.95) # keep 95% variance
    X_pca = pca.fit_transform(X_scaled)
    print(f"PCA: {X.shape[1]} -> {X_pca.shape[1]} components")
    
    X_train, X_test, y_train, y_test = train_test_split(X_pca, y_enc, test_size=0.2, random_state=42)
    
    models = {
        "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
        "DecisionTree": DecisionTreeClassifier(random_state=42),
        "KNN": KNeighborsClassifier(n_neighbors=5)
    }
    
    results = {}
    best_model = None
    best_acc = 0
    best_name = ""
    
    for name, model in models.items():
        model.fit(X_train, y_train)
        pred = model.predict(X_test)
        acc = accuracy_score(y_test, pred)
        cv = cross_val_score(model, X_pca, y_enc, cv=5).mean()
        results[name] = {"accuracy": acc, "cv_score": cv}
        print(f"{name}: Accuracy={acc:.3f} CV={cv:.3f}")
        if acc > best_acc:
            best_acc = acc
            best_model = model
            best_name = name
    
    # Save best model + preprocessing
    out_dir = Path(__file__).parent.parent / "backend" / "ml_service"
    out_dir.mkdir(parents=True, exist_ok=True)
    
    with open(out_dir / "model.pkl", "wb") as f:
        pickle.dump({
            "model": best_model,
            "scaler": scaler,
            "pca": pca,
            "label_encoder": le,
            "feature_cols": feature_cols,
            "best_model_name": best_name
        }, f)
    
    # Also save metrics
    metrics = {
        "best_model": best_name,
        "results": results,
        "pca_components": int(X_pca.shape[1]),
        "labels": list(le.classes_),
        "confusion_matrix": confusion_matrix(y_test, best_model.predict(X_test)).tolist()
    }
    with open(Path(__file__).parent / "metrics.json", "w") as f:
        json.dump(metrics, f, indent=2)
    
    with open(Path(__file__).parent / "metrics.txt", "w") as f:
        f.write(f"Best Model: {best_name}\n")
        for k,v in results.items():
            f.write(f"{k}: {v}\n")
    
    print(f"Saved model to {out_dir / 'model.pkl'}")
    print(f"Best: {best_name}")

if __name__ == "__main__":
    train()
